### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by koep**
I want to use your solr exporter in my Kubernetes setup (for simplicity I want my k8s cluster to pull the image from Docker Hub).

For this I updated the Dockerfile and created an automated build (https://hub.docker.com/r/koep/prometheus-solr-exporter/).

In case you want to pull this we should update the README.md accordingly. Otherwise just close this PR :)

### CODE REVIEW

**Review by noony — APPROVED** [review]

**Comment by noony** [comment]
What's the difference @koep ? Image is already available on docker hub https://hub.docker.com/r/noony/prometheus-solr-exporter/

**Comment by noony** [comment]
I already had a docker hub image : https://hub.docker.com/r/noony/prometheus-solr-exporter/

**Comment by koep** [comment]
Oh sorry I missed that it's already on docker hub (maybe update the docs?).

I guess the only difference is that with the new Dockerfile the build happens inside a docker container. This way the build can be automated on docker hub (meaning you don't have to login to docker hub and push the image) and you don't need Golang on your host.

Also you don't have to pull a "binary blob" from docker hub, but you can see the actual dockerfile and reproduce it yourself. https://docs.docker.com/docker-hub/builds/

**Comment by noony** [comment]
Yes ok I see the difference, thanks, I will merge this PR and think about put in place automated build and update the documentation 👍 .

**Comment by koep** [comment]
Also the build happens on every git commit push. I think you can even configure docker tags to match github tags etc.
Replacing it will be pretty straight forward I think!

**Comment by noony** [comment]
Yes, Thanks ! Tonight I will put that in place, thanks

**Comment by noony** [comment]
I close this PR. Thanks I prefer to not automatically build for now. I've added the link to docker image in README.md

**Pull request closed without merging**
